-- 1. Clients Table
CREATE TABLE IF NOT EXISTS Clients (
    ClientID VARCHAR(64) PRIMARY KEY,
    PIN VARCHAR(100) NOT NULL,
    Balance DECIMAL(10,2) DEFAULT 0.00,
    QR VARCHAR(255) NOT NULL,
    LastModified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Active TINYINT
);

-- 2. Farms Table
CREATE TABLE IF NOT EXISTS Farms (
    FarmID INT AUTO_INCREMENT PRIMARY KEY,
    FarmName VARCHAR(255) NOT NULL
);

-- 3. Transactions Table
CREATE TABLE IF NOT EXISTS Transactions (
    TransactionID INT AUTO_INCREMENT PRIMARY KEY,
    Total DECIMAL(10,2) NOT NULL,
    TransactionDate DATETIME NOT NULL,
    FarmID INT NOT NULL,
    ClientID VARCHAR(64) NOT NULL,
    CONSTRAINT fk_Transactions_Clients FOREIGN KEY (ClientID) REFERENCES Clients(ClientID),
    CONSTRAINT fk_Transactions_Farms FOREIGN KEY (FarmID) REFERENCES Farms(FarmID)
);

-- 4. Administrators Table
CREATE TABLE IF NOT EXISTS Administrators (
    CognitoUser VARCHAR(255) PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    LastModified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);