name: Deploy Infrastructure

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Validate CloudFormation Template
        run: aws cloudformation validate-template --template-body file://infrastructure/stack.yaml

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --stack-name garrettgrowersPOSstack \
            --template-file infrastructure/stack.yaml \
            --parameter-overrides \
                DBUsername=${{ secrets.DB_USERNAME }} \
                DBPassword=${{ secrets.DB_PASSWORD }} \
            --capabilities CAPABILITY_NAMED_IAM
